baseURL = "https://evanemily.com"
languageCode = "en-us"
title = "Evan and Emily Wedding"
theme = "spectral"

[params]
fancytitle = "Emily Waterman + Evan Farrell"
description = "Cazenovia, NY<br/ ><div style='font-size:25px'>MAY 25TH 2019</div>"
copyright = "Evan Farrell"

[params.one]
enable = true
title = "Come Celebrate with us"
body = "May 25th, 2018</br> Ceremony & Reception: 6PM</br>Skyline Lodge&mdash;Highland Forest"

[params.two]
enable = true

[[params.two.section]]
img = ""
title = "Evan and Emily"
body = ""

[[params.two.section]]
img = "img/evan.jpg"
title = "Evan"
body = "Evan loves to build things (like our kitchen table!), and go climbing and hiking. He is a site reliability engineer at Security Scorecard. Evan met Emily when he was working in State College after college. Evan proposed to Emily on a mountain in West Virginia after they decided they wanted to get married."

[[params.two.section]]
img = "img/emily.jpg"
title = "Emily"
body = "Emily loves to go hiking, backpacking, and birding. She is a postdoctoral scholar at University of New Hampshire who works on sexual and dating violence prevention. Emily met Evan went she was getting her PhD at Penn State. As she likes to say, \"we met online, like any self-respecting millennials.\""

[params.three]
enable = true
title = "Registry"
body = "<a href='/registry' class='button special'>View our Registry</a>"

[[params.menu.main]]
url = '/'
title = "Home"

[[params.menu.main]]
url = '/registry'
title = "Registry"

[[params.menu.main]]
url = '/things-to-do'
title = "Things To Do"
